name: clightning_rpc
description: Generic and Fast way to have your app connected with core lightning with dart and Unix socket
version: 0.0.2-beta.4
homepage: https://github.com/dart-lightning/lndart.clightning
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0

dependencies:
  json_rpc_2: ^3.0.1
  jsonrpc2: ^3.0.1
  cln_common:
    git:
      url: https://github.com/dart-lightning/lndart.cln
      path: packages/cln_common

#dependency_overrides:
#  cln_common:
#    path: ../cln_common
